version: '3.4'

services:
  shopping.api:
    container_name: shoppingapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://shoppingdb:27017"
#     - ASPNETCORE_URLS=https://+:443;http://+:80
    depends_on:
      - shopping.db
    ports:
      - "8000:80"
#     - "443"
#    volumes:
#      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
#      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  shopping.client:
    container_name: shoppingclient
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - "ShoppingAPIUrl=http://shoppingapi"
    depends_on:
      - shopping.db
      - shopping.api
    ports:
      - "8001:80" 

  shopping.db:
    container_name: shoppingdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db