name: Build Docker Images

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Shopping.API 
      run: docker build . --file Shopping.API/Dockerfile --tag my-image-name:$(date +%s)
    - name: Build Shopping.Client 
      run: docker build . --file Shopping.Client/Dockerfile --tag my-image-name:$(date +%s)
